# Generated by Django 2.2.16 on 2020-09-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_std'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='std',
        ),
    ]
