# Generated by Django 2.2.16 on 2020-09-04 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_book_student"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Book",
        ),
    ]
