# Generated by Django 2.2.16 on 2020-09-04 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_std"),
        ("home", "0006_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Student",
        ),
    ]
