# Generated by Django 2.2.16 on 2020-09-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_auto_20200904_1114"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.BigIntegerField()),
            ],
        ),
    ]
